name: Release using custom scripts

on:
  workflow_dispatch

jobs:
  determine_version:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: santhosh162000/gradlesonar1  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: gradlesonar1  # The step ID to refer to later.

      - run: echo "gradlesonar1 is at version ${{ steps.gradlesonar1.outputs.tag }}"

