name: Release using custom scripts

on:
  workflow_dispatch

jobs:
  determine_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: santhosh162000/gradlesonar1  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: gradlesonar1  # The step ID to refer to later.

      - run: echo "gradlesonar1 is at version ${{ steps.gradlesonar1.outputs.tag }}"

      - name: Get Latest Commit Message
        id: latest_commit_message
        run: |
          echo "::set-output name=commit_message::$(git log --format=%B -n 1)"

      - run : echo "Latest commit message is ${{ steps.latest_commit_message.outputs.commit_message }}"  

      - name: Testing some features
        run: |
          CURRENT_VERSION=${{ steps.gradlesonar1.outputs.tag }}
          MAJOR=$(echo $CURRENT_VERSION | awk -F. '{print $1}')
          echo "$MAJOR"

