name: Release using custom scripts

on:
  workflow_dispatch

jobs:
  determine_version:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: octokit/rest.js  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: octokit  # The step ID to refer to later.

      - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"

