name: Build and release SDK for learning

on: 
  workflow_dispatch

jobs:
  release-project:
    name: Release SDK
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download contents
        uses: actions/download-artifact@v2
        with:
          name: SDK

      - name: Archive contents
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip   

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload SDK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip         


  build-project:
    name: Build SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew    
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build  

      - name: Upload SDK
        uses: actions/upload-artifact@v2   
        with:
          name: SDK
          path: build/
